"""Public backend interface for the StrideX Streamlit application."""

from .backend import (
    APP_VERSION,
    DISCLAIMER,
    build_report_html,
    create_assessment_record,
    detect_risk,
    generate_simulated_gait_metrics,
    get_ai_insights,
    get_capabilities,
    get_dashboard_alerts,
    get_dashboard_statistics,
    get_device_status,
    get_gait_score,
    get_recent_assessments,
    get_recommendation,
    get_simulated_sensor_data,
    get_weekly_trend,
    history_to_csv,
    make_demo_history,
    process_gait_images,
    process_gait_video,
    run_full_stridex_analysis,
    run_full_strideX_analysis,
)

__all__ = [
    "APP_VERSION",
    "DISCLAIMER",
    "build_report_html",
    "create_assessment_record",
    "detect_risk",
    "generate_simulated_gait_metrics",
    "get_ai_insights",
    "get_capabilities",
    "get_dashboard_alerts",
    "get_dashboard_statistics",
    "get_device_status",
    "get_gait_score",
    "get_recent_assessments",
    "get_recommendation",
    "get_simulated_sensor_data",
    "get_weekly_trend",
    "history_to_csv",
    "make_demo_history",
    "process_gait_images",
    "process_gait_video",
    "run_full_stridex_analysis",
    "run_full_strideX_analysis",
]